### ISSUE TITLE
[PSPE] Move wrongly when run on stairs and slabs.

### ISSUE THREAD

**Issue by MikuSnow** [ProtocolSupport/ProtocolSupportPocketStuff#64] opened 2018-06-07 06:57 UTC
![image](https://user-images.githubusercontent.com/7759441/41083109-f8bfde84-6a62-11e8-8b26-31666e2b3e0f.png)

Run fast on it.
Player will tp back by server.

**Comment by Wesley-VanNeck** [comment] 2018-06-07 07:01
@MikuSnow  already known and duplicated

**Comment by 7kasper** [comment] 2018-06-18 08:34
Duplicate of #34.

**Closed by 7kasper** 2018-06-18 08:34 UTC
